server:
  address: "0.0.0.0"
  port: 8080
  tls:
    enabled: false
  
  # Admin API authentication (disabled for dev)
  admin_api_key: ""
  admin_api_header: "X-Admin-API-Key"

development:
  enabled: true
  debug_mode: true
  admin_endpoints:
    enabled: true

logging:
  level: "debug"

metrics:
  enabled: true