server:
  address: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  shutdown_timeout: 30s
  
  tls:
    enabled: false
    min_version: "1.2"
  
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization", "X-Client-ID", "X-Session-ID"]
    allow_credentials: false
    max_age: 86400
  
  middleware:
    compression:
      enabled: true
      level: 6
      types: ["application/json", "text/html", "text/css", "application/javascript"]
    
    rate_limit:
      enabled: false
      rps: 1000
      burst: 2000
      window_size: 1m
    
    request_logging:
      enabled: true
      include_body: false
      exclude_paths: ["/health", "/metrics"]
      include_headers: ["User-Agent", "X-Forwarded-For"]
  
  health_check:
    enabled: true
    endpoint: "/health"
    detailed: true

logging:
  level: "debug"
  format: "json"
  
  output:
    console:
      enabled: true
      colorized: true
    file:
      enabled: false
      path: "logs/mcpeg.log"
      max_size: 100  # MB
      max_backups: 10
      max_age: 30    # days
      compress: true
  
  structured:
    include_trace_id: true
    include_span_id: true
    include_caller: true
    include_stack: false

metrics:
  enabled: true
  address: "0.0.0.0"
  port: 9090
  
  prometheus:
    enabled: true
    endpoint: "/metrics"
    namespace: "mcpeg"
    subsystem: "gateway"
  
  collection:
    http: true
    system: true
    business: true
    system_interval: 15s

registry:
  discovery:
    static:
      enabled: true
      services:
        - name: "test-service"
          type: "mcp"
          endpoints:
            - address: "localhost"
              port: 8081
              weight: 100
              tags: ["test", "development"]
          metadata:
            version: "1.0.0"
            environment: "development"
    
    consul:
      enabled: false
      address: "localhost:8500"
      service_prefix: "mcpeg"
      tags: ["mcp", "gateway"]
    
    kubernetes:
      enabled: false
      namespace: "default"
      label_selector: "app=mcpeg-service"
    
    file:
      enabled: false
      path: "config/services"
      watch_enabled: true
      watch_interval: 30s
  
  load_balancer:
    strategy: "round_robin"  # round_robin, least_connections, weighted, hash, random
    health_aware: true
    
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      recovery_timeout: 30s
      half_open_max_requests: 3
  
  health_checks:
    enabled: true
    interval: 30s
    timeout: 5s
    
    http:
      enabled: true
      path: "/health"
      method: "GET"
      headers:
        User-Agent: "MCPEG-HealthChecker/1.0"
      expected_status: [200, 204]
    
    tcp:
      enabled: false

security:
  api_key:
    enabled: false
    header: "X-API-Key"
    keys: []
  
  jwt:
    enabled: false
    secret: ""
    algorithm: "HS256"
    validate_expiry: true
    validate_issuer: false
    validate_audience: false
  
  validation:
    enabled: true
    strict_mode: false
    validate_body: true

development:
  enabled: true
  hot_reload: true
  debug_mode: true
  profiler_port: 6060
  
  admin_endpoints:
    enabled: true
    prefix: "/admin"
    config_reload: true
    service_discovery: true
    health_checks: true