# TLS Configuration for MCPEG Production Deployment

# Certificate configuration
certificates:
  # Server certificate for HTTPS
  server:
    cert_file: "/etc/mcpeg/certs/server.crt"
    key_file: "/etc/mcpeg/certs/server.key"
    
  # Client CA for mutual TLS
  client_ca:
    ca_file: "/etc/mcpeg/certs/client_ca.crt"
    verify_client: true
    
  # Certificate rotation
  rotation:
    enabled: true
    check_interval: "24h"
    renewal_threshold: "30d"  # Renew when cert expires in 30 days

# TLS protocol configuration
protocol:
  min_version: "1.3"  # TLS 1.3 minimum (bar-raising)
  max_version: "1.3"  # Force TLS 1.3 only
  
  # Strong cipher suites only
  cipher_suites:
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_CHACHA20_POLY1305_SHA256"
    - "TLS_AES_128_GCM_SHA256"  # Fallback for compatibility
    
  # Curve preferences (strongest first)
  curve_preferences:
    - "X25519"
    - "P-384"
    - "P-256"
    
# Security headers for HTTPS
security_headers:
  strict_transport_security:
    enabled: true
    max_age: "31536000"  # 1 year
    include_subdomains: true
    preload: true
    
  content_security_policy:
    enabled: true
    policy: |
      default-src 'none';
      connect-src 'self';
      script-src 'none';
      style-src 'none';
      img-src 'none';
      font-src 'none';
      object-src 'none';
      media-src 'none';
      frame-src 'none';
      
  x_content_type_options: "nosniff"
  x_frame_options: "DENY"
  x_xss_protection: "1; mode=block"
  referrer_policy: "strict-origin-when-cross-origin"
  
  # Custom security headers
  custom_headers:
    "X-MCP-Server": "MCPEG/1.0"
    "X-Security-Level": "enhanced"

# CORS configuration for web clients
cors:
  enabled: true
  allowed_origins:
    - "https://claude.ai"
    - "https://*.anthropic.com"
    - "https://localhost:*"  # Development only
    
  allowed_methods:
    - "POST"
    - "OPTIONS"
    
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-MCP-Client-Info"
    - "X-Request-ID"
    
  exposed_headers:
    - "X-MCP-Server-Info"
    - "X-Rate-Limit-Remaining"
    - "X-Response-Time"
    
  allow_credentials: true
  max_age: "3600"  # 1 hour preflight cache

# Rate limiting configuration
rate_limiting:
  # Global rate limits
  global:
    enabled: true
    requests_per_second: 100
    burst: 200
    
  # Per-IP rate limits  
  per_ip:
    enabled: true
    requests_per_second: 10
    burst: 20
    window: "1m"
    
  # Per-method rate limits
  per_method:
    "initialize": 
      requests_per_minute: 5
      burst: 2
    "tools/call":
      requests_per_minute: 100
      burst: 10
    "resources/read":
      requests_per_minute: 200
      burst: 50

# Connection limits
connection_limits:
  max_concurrent: 1000
  max_per_ip: 10
  idle_timeout: "120s"
  read_timeout: "30s"
  write_timeout: "30s"
  
# DDoS protection
ddos_protection:
  enabled: true
  
  # Connection rate limiting
  new_connections_per_second: 10
  max_connections_per_ip: 5
  
  # Request size limits
  max_request_size_mb: 10
  max_header_size_kb: 32
  
  # Suspicious pattern detection
  pattern_detection:
    enabled: true
    unusual_user_agents: true
    rapid_requests: true
    invalid_methods: true
    
# Monitoring and alerting
monitoring:
  # TLS monitoring
  tls:
    log_handshake_failures: true
    log_certificate_issues: true
    alert_on_weak_ciphers: true
    
  # Security event logging
  security_events:
    log_all_connections: false
    log_failed_auth: true
    log_rate_limit_hits: true
    log_ddos_attempts: true
    
  # Metrics collection
  metrics:
    tls_handshake_duration: true
    connection_counts: true
    request_sizes: true
    error_rates: true

# Development overrides
development:
  # Relaxed settings for local development
  allow_insecure: false  # Still require TLS in dev
  self_signed_certs: true
  skip_client_verification: true
  
  # Additional allowed origins for development
  cors_dev_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:*"
    
  # Relaxed rate limits
  rate_limits:
    global_requests_per_second: 1000
    per_ip_requests_per_second: 100